show databases;
use gram_panchayat;
show tables;
select * from citizen;
select * from certificate_type;
select* from certificate_application;
select * from panchayat_office;
update citizen c join panchayat_office po on c.village_name=po.village_name set c.address=po.village_name;
alter table certificate_application drop issued_date;
alter table certificate_application add column certificate_id int ,add column office_id int;
update certificate_application ca join certificate_type ct on ca.certificate_name=ct.certificate_name set ca.certificate_id=ct.certificate_type_id;
alter  table certificate_application drop certificate_name;
update certificate_application set office_id=1 where application_id=1001;
update certificate_application set office_id=2 where application_id=1002;
update certificate_application set office_id=3 where application_id=1003;
update certificate_application set office_id=4 where application_id=1004;
update certificate_application set office_id=5 where application_id=1005;
alter table certificate_application add constraint fn_key foreign key(citizen_id) references citizen (citizen_id);
describe certificate_application;
alter table certificate_application add constraint cert_id foreign key (certificate_id) references certificate_type(certificate_type_id);
alter table certificate_application add constraint off_id foreign key (office_id) references panchayat_office(office_id);
desc certificate_application;
insert into certificate_application values (1009,1010,'2026-07-20',"local bot",'pending',26,"gp202610",6,10);
insert into certificate_application values (1009,1010,'2026-07-20',"local bot",'pending',26,"gp202610",5,10);
delete from citizen where citizen_id=101;
delete from certificate_type where certificate_type_id=1;
select * from citizen;
select * from certificate_application;
select full_name from citizen order by full_name asc;
select distinct village_name from panchayat_office;
select distinct certificate_name from certificate_type;
select distinct office_name from panchayat_office;
select * from certificate_application where application_status="under review";
select * from  panchayat_office where village_name="ramapuram";
select * from certificate_application where year( application_date)='2026';
select * from certificate_application order by application_date;
select * from certificate_type where certification_name ='income';
select * from certificate_type where certificate_name ='income' union  select * from certificate_type where certificate_name ='residance';
select * from certificate_application where month(application_date)=1 union select * from certificate_application where month(application_date)=2;
select full_name from citizen where village_name="ramapuram" union select full_name from citizen where village_name="lakshmipuram";
select full_name from citizen c join certificate_application ca  on c.citizen_id= ca.citizen_id join certificate_type ct on ca.certificate_id= ct.certificate_type_id where ct.certificate_name="property certificate";
select full_name from citizen where citizen_id in(select citizen_id from certificate_application ca join certificate_type ct on ca.certificate_id=ct.certificate_type_id where ct.certificate_name="property certificate") and citizen_id in(select citizen_id from certificate_application ca join certificate_type ct on ca.certificate_id=ct.certificate_type_id where ct.certificate_name="residence certificate");
select full_name from citizen where citizen_id in(select citizen_id from certificate_application where year(application_date)=2025)and citizen_id in(select citizen_id from certificate_application where year(application_date)=2026);
select full_name from citizen where citizen_id in(select citizen_id from certificate_application ca join certificate_type ct on ca.certificate_id=ct.certificate_type_id where ct.certificate_name="property certificate") and citizen_id not in(select citizen_id from certificate_application ca join certificate_type ct on ca.certificate_id=ct.certificate_type_id where ct.certificate_name="residence certificate");
select full_name from citizen where citizen_id not in(select citizen_id from certificate_application where year(application_date)=2025)and citizen_id in(select citizen_id from certificate_application where year(application_date)=2026);
insert into certificate_application values(1006,106,"2026-01-31","personal","rejected",30.00,"gp202657",6,6);
delete from citizen where citizen_id=101;
select full_name from citizen where citizen_id in(select citizen_id from certificate_application);
select full_name from citizen where village_name in ( select distinct c.village_name from citizen c join certificate_application ca on c.citizen_id=ca.citizen_id join certificate_type ct on ca.certificate_id=ct.certificate_type_id where ct.certificate_name="property certificate");
select full_name from citizen where citizen_id not in(select citizen_id from certificate_application);
select office_name from panchayat_office where office_id not in (select office_id from certificate_application);
select full_name from citizen c where exists(select * from certificate_application ca where ca.Citizen_id=c.citizen_id);
select certificate_name from certificate_type ct where exists(select * from certificate_application ca where ca.certificate_id=ct.certificate_type_id);
select full_name from citizen c where not exists (select * from certificate_application ca where ca.citizen_id=c.citizen_id);
select certificate_name from certificate_type ct where not exists( select * from certificate_application ca where ca.certificate_id=ct.certificate_type_id);
select full_name, date_of_birth from citizen where date_of_birth>any(select date_of_birth from citizen where village_name="ramapuram");
select full_name, date_of_birth from citizen where date_of_birth>all(select date_of_birth from citizen where village_name="ramapuram");
