show databases;
use gram_panchayat_db;
show tables;
select * from citizen;
select upper(full_name) from citizen;
select lower(village_name) from citizen;
select length(full_name) from citizen;
select substring(reference_number,1,4) from certification_application;
select concat(full_name,'-',village_name) from citizen;
select * from certification_application;
select replace(certificate_name,'certificate','cert') from certification_application;
select trim(certificate_name) as removing_spaces from certification_application;
select left(full_name,instr(full_name,' '))  from citizen;
select concat('citizen: ',full_name,"\n",'village: ',village_name) as details from citizen;
select * from certification_application where left(reference_number,6)='gp2026';
select round(fee_paid) as fees from certification_application;
select * from  certification_application;
update certification_application set fee_paid=23.5 where application_id=1005;
select abs(processing_days-10) as days from certification_type;
select sqrt(processing_days) as square from certification_type;
select mod(processing_days,3) as moddd from certification_type;
select power(processing_days,2) as powerr from certification_type;
select round(fee_paid,1) from  certification_application;
select floor(fee_paid) from certification_application;
select ceil(fee_paid) from certification_application;
select rand() *100;
select sqrt(processing_days) as square from certification_type;
select processing_days*2 from certification_type;
select * from certification_type;
select * from certification_application;
select curdate() as today_DATE;
SELECT current_date(),current_time() as date_time;
select year(application_date) from  certification_application;
select month(application_date) from  certification_application;
select day(application_date) from  certification_application;
select  date_add(application_date,interval processing_days day)as expected_issued_date from certification_application  join certification_type;
select date_add(application_date, interval 30 day) from certification_application;
select date_sub(application_date,interval 7 day) from certification_application;
select datediff(curdate(),application_date)from certification_application;
select * from certification_application where year(application_date)=year(curdate());
select cast(application_fee as signed) from certification_type;
select cast(processing_days as char) from certification_type;
select cast(application_date as datetime) from certification_application;
select cast(fee_paid as char) from certification_application;
select cast(processing_days as decimal(10,2)) from certification_type;
select cast(processing_days as decimal(10,2))*2 from certification_type;
